# Generated by Django 2.1.5 on 2019-01-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190121_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song_artist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Song'),
        ),
    ]
